Updating index.js to match Node v4.3 format
AWSinAction/lambda pull request #6
Opened 2017-03-13 15:35 UTC by mcloide

This merge request will update the callbacks for `succeed` and `fail` based on AWS documentation -  http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-using-old-runtime.html#transition-to-new-nodejs-runtime - aligning with the change for runtime to be Node v4.3.

This comes as a request from AWS on deprecation of Node v0.10 - https://forums.aws.amazon.com/ann.jspa?annID=4345

What it does:

context.succeed is replaced by

```
context.callbackWaitsForEmptyEventLoop = false;
callback(null, 'Success message');
```

context.fail is replaced by 

```
context.callbackWaitsForEmptyEventLoop = false;
callback(err, 'Fail message');
```

Also replaced the if statements for a switch to improve readability.

**Note** this was tested on a real aws lambda before publishing this PR. No errors reported by the lambda.

2017-03-13 15:36 UTC, mcloide commented
@michaelwittig code updated.

2017-03-14 17:37 UTC, michaelwittig requested changes
I just added two small comments. Let mw know what you think.

2017-03-14 17:37 UTC, michaelwittig commented on index.js
> +					callback(err, 'Failed result');
usually, if the first parameter is set (an error), the second one is not passed.

2017-03-14 17:37 UTC, michaelwittig commented on index.js
> +					callback(null, 'Success message');
is a 2nd parameter needed? It will change the behaviour of the program.

2017-03-14 20:41 UTC, mcloide commented on index.js
> +					callback(null, 'Success message');
No. It was suggested by AWS. Basically the callback will report anything as success as long it doesn't pass an Error object. I will remove and update.

2017-03-14 20:49 UTC, mcloide commented on index.js
> +					callback(err, 'Failed result');
👍

2017-03-14 20:52 UTC, mcloide commented
Updated as requested.

2017-03-15 15:56 UTC, michaelwittig approved these changes

2017-03-15 15:56 UTC, merged

2017-03-15 15:56 UTC, michaelwittig commented
thanks @mcloide !

2017-03-15 16:06 UTC, mcloide commented
@michaelwittig no problem. Happy to contribute.